### ISSUE TITLE
无法运行代码

### ISSUE THREAD

**Issue by YuantingMaSC** [THUDM/GraphMAE#66]
你好，我尝试运行你的代码，但是无法下载demo数据集，请问是否有其他方法可以解决？
以下是报错
Traceback (most recent call last):
  File ".\main_graph.py", line 206, in <module>
    main(args)
  File ".\main_graph.py", line 140, in main
    graphs, (num_features, num_classes) = load_graph_classification_dataset(dataset_name, deg4feat=deg4feat)
  File "F:\MYT\GraphMAE\graphmae\datasets\data_util.py", line 133, in load_graph_classification_dataset
    dataset = TUDataset(dataset_name)
  File "D:\ProgramData\anaconda3\envs\GraphMAE\lib\site-packages\dgl\data\tu.py", line 329, in __init__
    verbose=verbose, transform=transform)
  File "D:\ProgramData\anaconda3\envs\GraphMAE\lib\site-packages\dgl\data\dgl_dataset.py", line 311, in __init__
    transform=transform)
  File "D:\ProgramData\anaconda3\envs\GraphMAE\lib\site-packages\dgl\data\dgl_dataset.py", line 99, in __init__
    self._load()
  File "D:\ProgramData\anaconda3\envs\GraphMAE\lib\site-packages\dgl\data\dgl_dataset.py", line 190, in _load
    self._download()
  File "D:\ProgramData\anaconda3\envs\GraphMAE\lib\site-packages\dgl\utils\internal.py", line 626, in wrapper
    return func(self, *args, **kwargs)
  File "D:\ProgramData\anaconda3\envs\GraphMAE\lib\site-packages\dgl\data\dgl_dataset.py", line 158, in _download
    self.download()
  File "D:\ProgramData\anaconda3\envs\GraphMAE\lib\site-packages\dgl\data\dgl_dataset.py", line 318, in download
    download(self.url, path=zip_file_path)
  File "D:\ProgramData\anaconda3\envs\GraphMAE\lib\site-packages\dgl\data\utils.py", line 163, in download
    raise e
  File "D:\ProgramData\anaconda3\envs\GraphMAE\lib\site-packages\dgl\data\utils.py", line 149, in download
    raise RuntimeError("Failed downloading url %s" % url)
RuntimeError: Failed downloading url https://www.chrsmrrs.com/graphkerneldatasets/CORA.zip

**Comment by wuanjunruc** [comment]
根据网址，手动下载
